#! /bin/bash

source .env.public
TAR_BZ2_NAME=./pyodide.tar.bz2
DST_DIR=./scratch

if [ -f "${TAR_BZ2_NAME}" ];
then
    echo "[preinstall] pyodide.tar.bz2 already downloaded."
    exit
else
    # if file exist the it will be printed
    echo "[preinstall] Downloading pyodide from github build..."
fi


mkdir scratch -p
rm -rf $TAR_BZ2_NAME ${DST_DIR}/pyodide

curl -LJ -o ${TAR_BZ2_NAME} ${DOWNLOAD_URL}
tar -xf ./pyodide.tar.bz2
mv pyodide ${DST_DIR}
